"""Base class for tool wirers."""

from __future__ import annotations

import json
from abc import ABC, abstractmethod
from dataclasses import dataclass
from pathlib import Path


@dataclass
class WireResult:
    """Result of a wire/unwire operation."""

    success: bool
    message: str
    config_path: Path | None = None


class BaseWirer(ABC):
    """Abstract base for tool-specific wiring."""

    def __init__(self, project_dir: str | Path | None = None):
        self.project_dir = Path(project_dir) if project_dir else Path.cwd()
        self.hook_script = self._find_hook_script()

    def _find_hook_script(self) -> Path:
        """Locate the enforce_guard.py hook script."""
        # Check relative to project dir first
        candidates = [
            self.project_dir / "hooks" / "enforce_guard.py",
            Path(__file__).resolve().parent.parent.parent / "hooks" / "enforce_guard.py",
        ]
        for p in candidates:
            if p.exists():
                return p.resolve()
        # Default to the expected location
        return (self.project_dir / "hooks" / "enforce_guard.py").resolve()

    @property
    @abstractmethod
    def name(self) -> str:
        """Human-readable tool name."""

    @abstractmethod
    def wire(self) -> WireResult:
        """Install hooks/config for this tool."""

    @abstractmethod
    def unwire(self) -> WireResult:
        """Remove hooks/config for this tool."""

    @abstractmethod
    def status(self) -> str:
        """Return current wiring status: 'wired', 'not wired', or 'partial'."""


class BaseMcpWirer(BaseWirer):
    """Common logic for MCP-based wirers (Gemini, Codex)."""

    @abstractmethod
    def _config_path(self) -> Path:
        """Path to the tool's MCP configuration file."""

    @abstractmethod
    def _wrapper_path(self) -> Path:
        """Path where the MCP wrapper script should be written."""

    def _get_wrapper_script(self) -> str:
        """Get the content of the MCP wrapper script."""
        return f'''\
#!/usr/bin/env python3
"""Context Surgeon MCP wrapper for {self.name}.

Auto-generated by `consurg wire`. Intercepts tool calls and enforces scope.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from consurg.constants import WRITE_TOOLS
from consurg.enforce import resolve_tier
from consurg.guard.lockfile import GuardLockfile
from consurg.scope import load_scope

import urllib.request
import urllib.error


def evaluate_via_guard(port, tool_name, file_path):
    """Try to evaluate via running guard server."""
    url = f"http://127.0.0.1:{{port}}/evaluate"
    payload = json.dumps({{
        "tool_name": tool_name,
        "file_path": file_path,
        "tool_input": {{}},
    }}).encode()
    req = urllib.request.Request(url, data=payload, headers={{"Content-Type": "application/json"}})
    try:
        with urllib.request.urlopen(req, timeout=9) as resp:
            return json.loads(resp.read())
    except Exception:
        return None


def check_access(tool_name, file_path, cwd):
    """Check if access is allowed."""
    lockfile = GuardLockfile(cwd)
    port = lockfile.get_port()
    if port:
        result = evaluate_via_guard(port, tool_name, file_path)
        if result:
            return result.get("decision") == "allow"

    scope = load_scope(Path(cwd) / ".consurg.yaml")
    if scope is None or not scope.active:
        return True

    tier, _ = resolve_tier(file_path, scope)
    if tier <= 1:
        return False
    if tier <= 3 and tool_name in WRITE_TOOLS:
        return False
    return True


# MCP stdio server loop
def main():
    for line in sys.stdin:
        try:
            msg = json.loads(line.strip())
        except json.JSONDecodeError:
            continue

        if msg.get("method") == "tools/call":
            params = msg.get("params", {{}})
            tool_name = params.get("name", "")
            args = params.get("arguments", {{}})
            file_path = args.get("file_path", args.get("path", ""))
            cwd = str(Path.cwd())

            if file_path and not check_access(tool_name, file_path, cwd):
                response = {{
                    "jsonrpc": "2.0",
                    "id": msg.get("id"),
                    "error": {{
                        "code": -32000,
                        "message": f"[CONTEXT SURGEON] Access denied: {{file_path}}",
                    }},
                }}
                print(json.dumps(response), flush=True)
                continue

        # Pass through
        print(json.dumps(msg), flush=True)


if __name__ == "__main__":
    main()
'''

    def wire(self) -> WireResult:
        # Write MCP wrapper script
        wrapper = self._wrapper_path()
        wrapper.parent.mkdir(parents=True, exist_ok=True)
        wrapper.write_text(self._get_wrapper_script())

        # Update tool MCP config
        config_path = self._config_path()
        config_path.parent.mkdir(parents=True, exist_ok=True)

        if config_path.exists():
            try:
                config = json.loads(config_path.read_text())
            except json.JSONDecodeError:
                config = {}
        else:
            config = {}

        if "mcpServers" not in config:
            config["mcpServers"] = {}

        if "consurg" in config["mcpServers"]:
            return WireResult(
                success=True,
                message=f"Already wired to {self.name}",
                config_path=config_path,
            )

        config["mcpServers"]["consurg"] = {
            "command": "python",
            "args": [str(wrapper)],
        }

        config_path.write_text(json.dumps(config, indent=2))
        return WireResult(
            success=True,
            message=f"Wired to {self.name} (MCP server wrapper)",
            config_path=config_path,
        )

    def unwire(self) -> WireResult:
        # Remove from tool config
        config_path = self._config_path()
        if config_path.exists():
            try:
                config = json.loads(config_path.read_text())
                if "mcpServers" in config and "consurg" in config["mcpServers"]:
                    del config["mcpServers"]["consurg"]
                    config_path.write_text(json.dumps(config, indent=2))
            except json.JSONDecodeError:
                pass

        # Remove wrapper script
        wrapper = self._wrapper_path()
        if wrapper.exists():
            wrapper.unlink()

        return WireResult(success=True, message=f"Unwired from {self.name}")

    def status(self) -> str:
        config_path = self._config_path()
        if not config_path.exists():
            return "not wired"
        try:
            config = json.loads(config_path.read_text())
            if "consurg" in config.get("mcpServers", {}):
                wrapper = self._wrapper_path()
                return "wired" if wrapper.exists() else "partial"
        except (json.JSONDecodeError, KeyError):
            pass
        return "not wired"
